# Punch list t3-44 (R side): expected values for a PANELED Repeated Measures
# chart, computed by the real jamovi marshalling.
#
# The module's own simple `measures` path never facets (rmplotbuilder.b.R sets
# has_facet <- FALSE there; jamovi reaches RM panels through the crossed factor
# registry's "panel" role instead), so there is no single R call to compare a
# faceted shell payload against. But the CLAIM the shell's implementation makes
# is precise and testable: a panel variable on RM is BETWEEN subjects, so each
# panel is an independent repeated-measures analysis, exactly as each between
# group already is. Cousineau-Morey then normalises within panel x group.
#
# So the expectation is generated by running R's RM on each panel's SUBSET and
# recording its bars. If the shell's faceted build matches those bar for bar,
# the panel really is independent; if the shell had normalised across panels
# instead (borrowing one panel's grand mean for another's subjects) every
# within-method error bar would differ and this would say so.
#
# Usage: Rscript standalone/verify/rm-panels-render.R
# Writes: /tmp/ps-rm-panels/expected.json

tryCatch(invisible(Sys.setlocale("LC_ALL", "en_US.UTF-8")),
         warning = function(w) NULL, error = function(e) NULL)

.self <- gsub("~+~", " ", sub("--file=", "", grep("--file=", commandArgs(FALSE), value = TRUE)[1]), fixed = TRUE)
ROOT <- normalizePath(file.path(dirname(.self), "..", ".."))
setwd(ROOT)
OUT <- "/tmp/ps-rm-panels"
dir.create(OUT, showWarnings = FALSE, recursive = TRUE)
Sys.setenv(R_USER_CONFIG_DIR = file.path(OUT, "config"))
Sys.setenv(GB2_NO_BUNDLE_CACHE = "1")

if (!requireNamespace("jmvcore", quietly = TRUE)) {
    cat("jmvcore not available; skipping\n"); quit(status = 2)
}
suppressWarnings(suppressMessages({
    library(jmvcore); library(R6)
    source("R/palette_library.R"); source("R/style_library.R")
    source("R/utils.R")
    source("R/gb_family_core.R"); source("R/spec_explode.R"); source("R/widget.R")
    source("R/rmplotbuilder.h.R"); source("R/rmplotbuilder.b.R")
}))
.gb2_widget_js <- function() ""
environment(graphbuilder2_html) <- globalenv()

payloadOf <- function(res) {
    w <- res$widget
    html <- tryCatch(w$content, error = function(e) NULL)
    if (is.null(html))
        html <- tryCatch(w$.__enclos_env__$private$.content, error = function(e) "")
    m <- regmatches(html, regexec(
        "var __gb2_payload = (\\{.*?\\});\nvar __gb2_id = \"([^\"]+)\";", html))[[1]]
    if (length(m) != 3) stop("payload extraction failed")
    jsonlite::fromJSON(m[2], simplifyVector = FALSE)
}

# ------------------------------------------------------------------ fixture
# Deliberately UNBALANCED across panels and groups: with equal cell sizes a
# cross-panel normalisation bug can hide behind coincidentally equal grand
# means. Non-alphabetical panel levels catch an ordering assumption. Two NAs,
# in different measures, so the per-occasion filter is exercised.
set.seed(9312)
N <- 46
site_lv <- c("North", "East", "Central")
d <- data.frame(
    t1 = round(10 + 5 * stats::rnorm(N), 3),
    stringsAsFactors = FALSE)
d$t2 <- round(d$t1 + 2.5 + 2 * stats::rnorm(N), 3)
d$t3 <- round(d$t1 + 4.0 + 2 * stats::rnorm(N), 3)
d$site <- factor(sample(site_lv, N, TRUE, prob = c(0.5, 0.3, 0.2)),
                 levels = site_lv)
d$arm  <- factor(rep(c("Drug", "Placebo"), length.out = N))
d$t2[7]  <- NA
d$t3[19] <- NA

write.csv(d, file.path(OUT, "rmpanels.csv"), row.names = FALSE, na = "")

# ------------------------------------------------------------------ expected
# Each panel run on its own, which is what "the panel is a between-subjects
# cell" MEANS. Levels are taken from the factor, so an empty panel would show
# up as a missing entry rather than silently shifting the others.
cases <- list(
    list(name = "within_grouped", between = "arm",  method = "within"),
    list(name = "within_plain",   between = NULL,   method = "within"),
    list(name = "between_plain",  between = NULL,   method = "between"))

expected <- list()
for (cs in cases) {
    perPanel <- list()
    for (lv in levels(d$site)) {
        sub <- d[!is.na(d$site) & d$site == lv, , drop = FALSE]
        res <- rmplotbuilder(data = sub, measures = c("t1", "t2", "t3"),
                             betweenVar = cs$between, rm = NULL, rmCells = NULL,
                             bs = NULL, graphType = "line",
                             errorBarMethod = cs$method, chartSpec = "")
        p <- payloadOf(res)
        perPanel[[lv]] <- lapply(p$bars, function(b) list(
            x = b$x,
            group = if (is.null(b$group)) NA_character_ else as.character(b$group),
            mean = b$mean, se = b$se, n = b$n))
    }
    expected[[cs$name]] <- list(
        between = if (is.null(cs$between)) NA_character_ else cs$between,
        method = cs$method,
        panels = perPanel)
}

con <- file(file.path(OUT, "expected.json"), open = "wb")
writeLines(as.character(jsonlite::toJSON(expected, auto_unbox = TRUE,
                                         digits = NA, null = "null")),
           con, useBytes = TRUE)
close(con)
cat("wrote", file.path(OUT, "expected.json"), "\n")
