#!/bin/bash
# Build the self-contained single-file Pandion Plots:
#   standalone/dist/pandion-plots.html
# = index.html with every <script src> (templates, shell JS, PDF libraries,
# and the engine bundle from ../inst/widget/) inlined. The result runs from ANYWHERE -
# double-click, email, course page, web host - with no repo around it.
# This is also the fix for the only cross-directory dependency the dev page
# has: index.html reaches outside standalone/ for the engine, so a copied
# or moved standalone/ folder shows "chart engine failed to load".
#
# Usage: bash standalone/build-dist.sh
set -e
cd "$(dirname "$0")"

python3 - <<'EOF'
import re, os, pathlib

root = pathlib.Path(".")
html = (root / "index.html").read_text(encoding="utf-8")

def inline(src_attr, path):
    global html
    js = pathlib.Path(path).read_text(encoding="utf-8")
    # Value-preserving guard: "</script" inside a JS string would end the
    # inline block early; "<\/script" is the same string value.
    js = js.replace("</script", "<\\/script")
    tag = '<script src="%s"></script>' % src_attr
    assert html.count(tag) == 1, tag
    html = html.replace(tag, "<script>\n" + js + "\n</script>")

inline("templates/templates.js", "templates/templates.js")
inline("js/ps-stat.js", "js/ps-stat.js")
inline("js/ps-omv.js", "js/ps-omv.js")
inline("js/ps-xlsx.js", "js/ps-xlsx.js")
inline("js/ps-formula.js", "js/ps-formula.js")
inline("js/ps-data.js", "js/ps-data.js")
inline("vendor/jspdf.umd.min.js", "vendor/jspdf.umd.min.js")
inline("vendor/svg2pdf.umd.min.js", "vendor/svg2pdf.umd.min.js")
inline("../inst/widget/graphbuilder2.min.js", "../inst/widget/graphbuilder2.min.js")
inline("js/ps-shell.js", "js/ps-shell.js")
inline("js/ps-tour.js", "js/ps-tour.js")

# Stamp the generated-file warning. Anchored on the TAG SHAPE, not the
# product name: the old literal-string match silently no-opped after the
# Plot Studio -> Pandion Plots rename, so the marker never landed.
TITLE_TAG = re.compile(r"<title>[^<]*</title>")
assert len(TITLE_TAG.findall(html)) == 1, "expected exactly one <title>"
html = TITLE_TAG.sub(
    lambda m: m.group(0) +
        "\n<!-- GENERATED by standalone/build-dist.sh - do not hand-edit. -->",
    html, count=1)

os.makedirs("dist", exist_ok=True)
out = root / "dist" / "pandion-plots.html"
out.write_text(html, encoding="utf-8")
print("wrote", out, "-", out.stat().st_size, "bytes")
EOF
