#!/bin/bash
# Refresh the deployable website folder from the repo sources.
#
#   bash website/build.sh
#
# - Builds app/ (the "Try it in your browser" target) as a SPLIT,
#   CACHE-FRIENDLY copy of standalone/index.html: a small shell plus
#   the eleven scripts it loads, each under a content-hashed filename.
#   See "Why app/ is split" below.
# - Copies the standalone single-file build to the site root as the
#   portable download. Run standalone/build-dist.sh first if the
#   standalone sources changed.
# - Assets (brand mark, hero art, product screenshot) are committed
#   files; regenerate the screenshots with website/shots.mjs when the
#   app UI changes meaningfully.
#
# The website/ folder itself is what gets deployed to Cloudflare
# Pages - there is no build step on the Pages side.
#
# ---- Why app/ is split ----
# The portable download is one 3.5 MB file on purpose: it has to run
# from a USB stick with nothing around it. Serving that same file as
# the web app made every visit re-download the 2.1 MB chart engine,
# because a one-line change anywhere in the shell changes the bytes of
# the whole bundle and therefore its ETag. Split, the engine is its own
# file whose name only changes when the engine itself does, so a repeat
# visitor (and a visitor arriving after a shell-only release) pays for
# the shell alone. Filenames carry a content hash, so app/lib/* can be
# served immutable with no risk of a stale script outliving its shell;
# the cache headers live in website/_headers.
set -e
cd "$(dirname "$0")/.."

for f in standalone/index.html inst/widget/graphbuilder2.min.js; do
    [ -f "$f" ] || { echo "$f missing" >&2; exit 1; }
done

python3 - <<'EOF'
import hashlib, pathlib, re

root = pathlib.Path(".")
src_dir = root / "standalone"
app = root / "website" / "app"
lib = app / "lib"
lib.mkdir(parents=True, exist_ok=True)

html = (src_dir / "index.html").read_text(encoding="utf-8")

# The eleven <script src> tags, in load order. Everything else the app
# needs is inline, so this list plus the manifest and icons IS the app.
TAG = re.compile(r'<script src="([^"]+\.js)"></script>')
srcs = TAG.findall(html)
assert srcs, "no external scripts found in standalone/index.html"

keep, total = set(), 0
for s in srcs:
    path = (src_dir / s).resolve()
    assert path.is_file(), path
    data = path.read_bytes()
    digest = hashlib.md5(data).hexdigest()[:10]
    name = "%s.%s.js" % (path.name[:-3], digest)
    out = lib / name
    if not out.exists() or out.read_bytes() != data:
        out.write_bytes(data)
    keep.add(name)
    total += len(data)
    tag = '<script src="%s"></script>' % s
    assert html.count(tag) == 1, tag
    html = html.replace(tag, '<script src="lib/%s"></script>' % name)

# Drop hashed files left behind by earlier builds, or app/lib grows
# without bound and every deploy ships the dead copies.
dropped = 0
for old in lib.glob("*.js"):
    if old.name not in keep:
        old.unlink()
        dropped += 1

TITLE_TAG = re.compile(r"<title>[^<]*</title>")
assert len(TITLE_TAG.findall(html)) == 1, "expected exactly one <title>"
html = TITLE_TAG.sub(
    lambda m: m.group(0) +
        "\n<!-- GENERATED by website/build.sh - do not hand-edit. -->",
    html, count=1)

(app / "index.html").write_text(html, encoding="utf-8")

# Anything the standalone dev page reads from the repo (currently just
# the engine) is resolved above, so app/ is self-contained.
print("website/app/index.html rebuilt (%.0f KB shell + %d scripts, %.1f MB)"
      % (len(html.encode("utf-8")) / 1024, len(keep), total / 1e6))
if dropped:
    print("  pruned %d stale hashed script(s) from website/app/lib" % dropped)
EOF

# Installability. The app's <link rel="manifest"> is relative, so the manifest
# and its icons have to sit beside index.html in app/. Chrome needs HTTPS plus
# 192px and 512px icons, so this only does anything for the hosted copy: the
# portable download ignores a manifest it cannot fetch.
cp standalone/manifest.json website/app/manifest.json
mkdir -p website/app/icons
cp standalone/icons/pandion-192.png standalone/icons/pandion-512.png website/app/icons/
echo "website/app/manifest.json + icons refreshed"

# The "Download HTML" button serves this from our own origin. Depending on
# a GitHub release asset broke: CI attaches only *.jmo, so the link 404'd.
if [ ! -f standalone/dist/pandion-plots.html ]; then
    echo "standalone/dist/pandion-plots.html missing - run standalone/build-dist.sh first" >&2
    exit 1
fi
cp standalone/dist/pandion-plots.html website/pandion-plots.html
echo "website/pandion-plots.html refreshed (portable download, $(du -h website/pandion-plots.html | cut -f1))"

# Docs: the canonical guide is docs/user-guide.html; the site serves a copy
# at /docs/ so the two can never drift. The site copy then gets the site's
# header/footer chrome INJECTED (marker-wrapped, byte-reversible) so the
# guide nests inside the website: same content, site nav on top. The
# canonical file stays chrome-free because it also ships inside the jamovi
# module, where site links would be broken. verify-accessibility.mjs strips
# the SITE-CHROME blocks and asserts what remains is byte-identical to the
# canonical, so content drift is still impossible.
mkdir -p website/docs
cp docs/user-guide.html website/docs/index.html
python3 - <<'EOF'
import pathlib, re

p = pathlib.Path("website/docs/index.html")
html = p.read_text(encoding="utf-8")
assert "SITE-CHROME" not in html, "canonical guide must not carry site chrome"

M0, M1 = "<!-- SITE-CHROME START -->", "<!-- SITE-CHROME END -->"

# ---- head: favicon + canonical + chrome styles + shared nav toggle JS ----
HEAD = M0 + """
<link rel="icon" type="image/svg+xml" href="../assets/favicon.svg">
<link rel="apple-touch-icon" href="../assets/icon-180.png">
<link rel="canonical" href="https://pandionplots.com/docs/">
<style>
/* Re-hue the guide from its old teal to the site's cobalt. Only the
   hue-carrying variables move; grays and semantic colors stay the
   guide's own, so no contrast pairing regresses. Scoped :not() so the
   guide's dark theme keeps its own (separately overridden) values. */
:root:not([data-theme="dark"]){
  --accent:#375CA0; --accent2:#2c4a80; --accent-soft:#e8f0fb;
  --blue:#375CA0;
}
[data-theme="dark"]{
  --accent:#7fb0ea; --accent2:#9cc3f0; --accent-soft:#1d2c40;
}
/* The site header (same markup + behavior as gallery.html; styles scoped
   under .site-header so nothing leaks into the guide's classes). */
.site-header{position:sticky;top:0;z-index:60;background:rgba(255,255,255,.92);backdrop-filter:blur(8px);border-bottom:1px solid #dde5ee}
.site-header .sw{max-width:1080px;margin:0 auto;padding:0 24px;display:flex;align-items:center;gap:10px;height:60px}
.site-header .brand{display:flex;align-items:center;gap:10px;color:#192E49;text-decoration:none;font-weight:800;font-size:18px;letter-spacing:-.01em}
.site-header .brand:hover,.site-header a:hover{text-decoration:none}
.site-header .brand img{width:34px;height:34px}
.site-header .wing-dark{display:none}
.site-header .nav-links{margin-left:auto;display:flex;gap:4px}
.site-header .nav-links a{color:#22364d;text-decoration:none;font-size:14.5px;font-weight:600;padding:7px 12px;border-radius:7px}
.site-header .nav-links a:hover{background:#f4f7fb;color:#192E49}
.site-header .nav-links a[aria-current="page"]{color:#375CA0}
.site-header .nav-links a.nav-cta{color:#fff;background:#192E49;margin-left:6px}
.site-header .nav-links a.nav-cta:hover{background:#24405f}
.site-header .nav-toggle{display:none;align-items:center;justify-content:center;gap:8px;min-width:44px;min-height:44px;margin-left:auto;padding:8px 10px;border:1px solid #c3d0df;border-radius:8px;color:#192E49;background:#fff;font:inherit;font-size:14px;font-weight:700;cursor:pointer}
.site-header .nav-toggle:hover{border-color:#375CA0;color:#375CA0}
.site-header .nav-toggle:focus-visible,.site-header .nav-links a:focus-visible{outline:3px solid rgba(55,92,160,.24);outline-offset:2px}
.site-header .nav-toggle-icon,.site-header .nav-toggle-icon::before,.site-header .nav-toggle-icon::after{display:block;width:18px;height:2px;border-radius:999px;background:currentColor}
.site-header .nav-toggle-icon{position:relative}
.site-header .nav-toggle-icon::before,.site-header .nav-toggle-icon::after{position:absolute;left:0;content:""}
.site-header .nav-toggle-icon::before{top:-6px}
.site-header .nav-toggle-icon::after{top:6px}
/* The site footer, offset past the fixed guide sidebar on desktop. */
.site-footer{border-top:1px solid #dde5ee;padding:36px 0 48px;margin-left:var(--sidebar-w);background:var(--bg)}
/* right padding clears the guide's fixed back-to-top button (42px @ right:22px) */
.site-footer .sw{max-width:1080px;margin:0 auto;padding:0 84px 0 24px;display:flex;flex-wrap:wrap;gap:18px;align-items:center;color:#5f6f80;font-size:13.5px}
.site-footer .brand{display:flex;align-items:center;gap:8px;color:#192E49;text-decoration:none;font-weight:800;font-size:15px}
.site-footer .brand img{width:26px;height:26px}
.site-footer .wing-dark{display:none}
.site-footer a{color:#375CA0}
.site-footer a:hover{text-decoration:none}
.site-footer .foot-links{margin-left:auto;display:flex;flex-wrap:wrap;gap:10px 18px}
.site-footer .foot-links a{color:#5f6f80;text-decoration:none}
.site-footer .foot-links a:hover{color:#375CA0}
/* Make room: the guide's fixed sidebar and floating buttons start below
   the sticky header, and anchor jumps clear it. */
nav#sidebar{top:60px}
.btnrow{top:72px}
h1,h2,h3,h4{scroll-margin-top:76px}
html{scroll-padding-top:76px}
/* Two hamburgers would be ambiguous on mobile: the site one says Menu,
   so the guide drawer trigger gets a visible Contents label. */
#hamb::after{content:" Contents";font-size:13px;font-weight:600}
@media (max-width:900px){
  .hamb{top:72px}
  .btnrow{top:72px}
  /* the sidebar is a drawer here, so the footer reclaims its offset */
  .site-footer{margin-left:0}
}
@media (max-width:760px){
  html{scroll-padding-top:72px}
  .site-header .sw,.site-footer .sw{padding-inline:18px}
  .site-header .sw{min-height:60px;height:auto;flex-wrap:wrap;padding-block:8px}
  .site-header .nav-toggle{display:inline-flex}
  .site-header .nav-links{display:none;width:100%;margin:8px 0 2px;padding:8px 0 0;flex-direction:column;gap:2px;border-top:1px solid #dde5ee}
  .site-header .nav-links.is-open{display:flex}
  .site-header .nav-links a{width:100%;padding:9px 10px;border-radius:7px;font-size:14.5px}
  .site-header .nav-links a.nav-cta{margin:6px 0 0;padding:10px 14px;text-align:center}
  /* the open menu grows over the guide's floating buttons; hide them
     behind it rather than letting them ghost through the blur */
  .site-header:has(.nav-links.is-open)~.hamb,
  .site-header:has(.nav-links.is-open)~.btnrow{visibility:hidden}
}
/* The chrome follows the guide's own dark theme. */
[data-theme="dark"] .site-header{background:rgba(20,24,28,.92);border-color:var(--line)}
[data-theme="dark"] .site-header .brand{color:var(--ink)}
[data-theme="dark"] .site-header .wing-light,[data-theme="dark"] .site-footer .wing-light{display:none}
[data-theme="dark"] .site-header .wing-dark,[data-theme="dark"] .site-footer .wing-dark{display:inline}
[data-theme="dark"] .site-header .nav-links a{color:var(--ink)}
[data-theme="dark"] .site-header .nav-links a:hover{background:var(--bg3);color:var(--ink)}
[data-theme="dark"] .site-header .nav-links a[aria-current="page"]{color:var(--accent)}
[data-theme="dark"] .site-header .nav-links a.nav-cta{background:#375CA0;color:#fff}
[data-theme="dark"] .site-header .nav-toggle{background:var(--bg2);color:var(--ink);border-color:var(--line)}
[data-theme="dark"] .site-header .nav-links{border-color:var(--line)}
[data-theme="dark"] .site-footer{border-color:var(--line)}
[data-theme="dark"] .site-footer .brand{color:var(--ink)}
[data-theme="dark"] .site-footer .sw{color:var(--ink3)}
[data-theme="dark"] .site-footer .foot-links a{color:var(--ink3)}
@media print{.site-header,.site-footer{display:none}}
</style>
<script src="../assets/site-nav.js" defer></script>
""" + M1

# ---- the site header, injected AFTER the skip link so it stays the
# first focus stop (verify-interactions asserts this) ----
HEADER = M0 + """
<header class="site-header">
  <div class="sw">
    <a class="brand" href="../index.html">
      <img class="wing-light" src="../assets/pandion-wing.svg" alt="">
      <img class="wing-dark" src="../assets/pandion-wing-light.svg" alt="">
      Pandion Plots
    </a>
    <button class="nav-toggle" type="button" aria-expanded="false"
      aria-controls="site-nav">
      <span class="nav-toggle-icon" aria-hidden="true"></span>
      <span>Menu</span>
    </button>
    <nav class="nav-links" id="site-nav" aria-label="Site">
      <a href="../gallery.html">Gallery</a>
      <a href="./" aria-current="page">Docs</a>
      <a href="../index.html#downloads">Downloads</a>
      <a href="../about.html">About</a>
      <a href="../support.html">Support</a>
      <a class="nav-cta" href="../app/">Try it now</a>
    </nav>
  </div>
</header>
""" + M1

FOOTER = M0 + """
<footer class="site-footer">
  <div class="sw">
    <a class="brand" href="../index.html">
      <img class="wing-light" src="../assets/pandion-wing.svg" alt="">
      <img class="wing-dark" src="../assets/pandion-wing-light.svg" alt="">
      Pandion Plots
    </a>
    <span>Made by Torry Scott Dennis, PhD.</span>
    <nav class="foot-links" aria-label="Footer">
      <a href="../app/">Try it</a>
      <a href="../gallery.html">Gallery</a>
      <a href="../about.html#cite">How to cite</a>
      <a href="../about.html">About</a>
      <a href="../support.html">Support</a>
      <a href="../accessibility.html">Accessibility</a>
      <a href="https://github.com/torryscott/pandion">GitHub</a>
    </nav>
  </div>
</footer>
""" + M1

SKIP = '<a class="skip-link" href="#content">Skip to guide content</a>'
for anchor, block, where in [
    ("\n</head>", HEAD, "before"),
    (SKIP, HEADER, "after"),
    ("\n</body>", FOOTER, "before"),
]:
    assert html.count(anchor) == 1, anchor[:40]
    if where == "after":
        html = html.replace(anchor, anchor + "\n" + block)
    else:  # before a "\n</tag>" anchor: keep the block on its own lines
        html = html.replace(anchor, "\n" + block + anchor)

# The strip in verify-accessibility.mjs must restore the canonical
# byte-for-byte; prove it here too so the build can never ship otherwise.
stripped = re.sub(r"\n<!-- SITE-CHROME START -->.*?<!-- SITE-CHROME END -->",
                  "", html, flags=re.S)
canonical = pathlib.Path("docs/user-guide.html").read_text(encoding="utf-8")
assert stripped == canonical, "chrome injection is not byte-reversible"

p.write_text(html, encoding="utf-8")
print("website/docs/index.html: site chrome injected (reversible, %d marker blocks)"
      % html.count("<!-- SITE-CHROME START -->"))
EOF
rsync -a --exclude '.DS_Store' --exclude 'README.md' docs/img/ website/docs/img/
echo "website/docs refreshed ($(du -sh website/docs | cut -f1))"

# Version-drift guard: the site advertises a release number in several
# places. Warn loudly rather than quietly serving a stale one.
VERSION=$(grep '^Version:' DESCRIPTION | awk '{print $2}')
DRIFT=0
for page in website/index.html website/about.html website/download.html; do
    grep -q "$VERSION" "$page" || { echo "WARN: $page does not mention version $VERSION" >&2; DRIFT=1; }
done
grep -q "version: \"$VERSION\"" CITATION.cff || {
    echo "WARN: CITATION.cff is not at version $VERSION" >&2; DRIFT=1; }
# The app reports its own version in Help and diagnostics; about.html
# tells users to look there, so it must agree with the site. Check both
# things the site serves: the split web app (where the declaration now
# lives in the hashed shell script, not index.html) and the portable
# download. Anchored on the DECLARATION, since a bare version grep
# passes vacuously off a vendored library that contains the string.
grep -rq "APP_VERSION = \"$VERSION\"" website/app/lib || {
    echo "WARN: the web app does not declare APP_VERSION = $VERSION" >&2; DRIFT=1; }
grep -q "APP_VERSION = \"$VERSION\"" website/pandion-plots.html || {
    echo "WARN: the portable download does not declare APP_VERSION = $VERSION" >&2; DRIFT=1; }
# The downloads card states the portable file's size. It grew from 3.9 MB to
# 4.5 MB without anyone noticing, so check it here rather than trusting a
# number typed once. Decimal MB, which is what a browser reports on download.
SIZE_MB=$(python3 -c "import os;print(f'{os.path.getsize(\"website/pandion-plots.html\")/1e6:.1f}')")
grep -q "One file, about ${SIZE_MB} MB" website/index.html || {
    echo "WARN: the downloads card does not say ${SIZE_MB} MB (portable file size)" >&2
    DRIFT=1; }

if [ "$DRIFT" = "0" ]; then
    echo "version $VERSION consistent across the site + CITATION.cff"
else
    echo "ERROR: public version references are inconsistent" >&2
    exit 1
fi

node website/verify-accessibility.mjs
