#!/bin/bash
# Refresh the deployable website folder from the repo sources.
#
#   bash website/build.sh
#
# - Builds app/ (the "Try it in your browser" target) as a SPLIT,
#   CACHE-FRIENDLY copy of standalone/index.html: a small shell plus
#   the eleven scripts it loads, each under a content-hashed filename.
#   See "Why app/ is split" below.
# - Copies the standalone single-file build to the site root as the
#   portable download. Run standalone/build-dist.sh first if the
#   standalone sources changed.
# - Assets (brand mark, hero art, product screenshot) are committed
#   files; regenerate the screenshots with website/shots.mjs when the
#   app UI changes meaningfully.
#
# The website/ folder itself is what gets deployed to Cloudflare
# Pages - there is no build step on the Pages side.
#
# ---- Why app/ is split ----
# The portable download is one 3.5 MB file on purpose: it has to run
# from a USB stick with nothing around it. Serving that same file as
# the web app made every visit re-download the 2.1 MB chart engine,
# because a one-line change anywhere in the shell changes the bytes of
# the whole bundle and therefore its ETag. Split, the engine is its own
# file whose name only changes when the engine itself does, so a repeat
# visitor (and a visitor arriving after a shell-only release) pays for
# the shell alone. Filenames carry a content hash, so app/lib/* can be
# served immutable with no risk of a stale script outliving its shell;
# the cache headers live in website/_headers.
set -e
cd "$(dirname "$0")/.."

for f in standalone/index.html inst/widget/graphbuilder2.min.js; do
    [ -f "$f" ] || { echo "$f missing" >&2; exit 1; }
done

python3 - <<'EOF'
import hashlib, pathlib, re

root = pathlib.Path(".")
src_dir = root / "standalone"
app = root / "website" / "app"
lib = app / "lib"
lib.mkdir(parents=True, exist_ok=True)

html = (src_dir / "index.html").read_text(encoding="utf-8")

# The eleven <script src> tags, in load order. Everything else the app
# needs is inline, so this list plus the manifest and icons IS the app.
TAG = re.compile(r'<script src="([^"]+\.js)"></script>')
srcs = TAG.findall(html)
assert srcs, "no external scripts found in standalone/index.html"

keep, total = set(), 0
for s in srcs:
    path = (src_dir / s).resolve()
    assert path.is_file(), path
    data = path.read_bytes()
    digest = hashlib.md5(data).hexdigest()[:10]
    name = "%s.%s.js" % (path.name[:-3], digest)
    out = lib / name
    if not out.exists() or out.read_bytes() != data:
        out.write_bytes(data)
    keep.add(name)
    total += len(data)
    tag = '<script src="%s"></script>' % s
    assert html.count(tag) == 1, tag
    html = html.replace(tag, '<script src="lib/%s"></script>' % name)

# Drop hashed files left behind by earlier builds, or app/lib grows
# without bound and every deploy ships the dead copies.
dropped = 0
for old in lib.glob("*.js"):
    if old.name not in keep:
        old.unlink()
        dropped += 1

TITLE_TAG = re.compile(r"<title>[^<]*</title>")
assert len(TITLE_TAG.findall(html)) == 1, "expected exactly one <title>"
html = TITLE_TAG.sub(
    lambda m: m.group(0) +
        "\n<!-- GENERATED by website/build.sh - do not hand-edit. -->",
    html, count=1)

(app / "index.html").write_text(html, encoding="utf-8")

# Anything the standalone dev page reads from the repo (currently just
# the engine) is resolved above, so app/ is self-contained.
print("website/app/index.html rebuilt (%.0f KB shell + %d scripts, %.1f MB)"
      % (len(html.encode("utf-8")) / 1024, len(keep), total / 1e6))
if dropped:
    print("  pruned %d stale hashed script(s) from website/app/lib" % dropped)
EOF

# Installability. The app's <link rel="manifest"> is relative, so the manifest
# and its icons have to sit beside index.html in app/. Chrome needs HTTPS plus
# 192px and 512px icons, so this only does anything for the hosted copy: the
# portable download ignores a manifest it cannot fetch.
cp standalone/manifest.json website/app/manifest.json
mkdir -p website/app/icons
cp standalone/icons/pandion-192.png standalone/icons/pandion-512.png website/app/icons/
echo "website/app/manifest.json + icons refreshed"

# The "Download HTML" button serves this from our own origin. Depending on
# a GitHub release asset broke: CI attaches only *.jmo, so the link 404'd.
if [ ! -f standalone/dist/pandion-plots.html ]; then
    echo "standalone/dist/pandion-plots.html missing - run standalone/build-dist.sh first" >&2
    exit 1
fi
cp standalone/dist/pandion-plots.html website/pandion-plots.html
echo "website/pandion-plots.html refreshed (portable download, $(du -h website/pandion-plots.html | cut -f1))"

# Docs: the canonical guide is docs/user-guide.html; the site serves a copy
# at /docs/ so the two can never drift.
mkdir -p website/docs
cp docs/user-guide.html website/docs/index.html
rsync -a --exclude '.DS_Store' --exclude 'README.md' docs/img/ website/docs/img/
echo "website/docs refreshed ($(du -sh website/docs | cut -f1))"

# Version-drift guard: the site advertises a release number in several
# places. Warn loudly rather than quietly serving a stale one.
VERSION=$(grep '^Version:' DESCRIPTION | awk '{print $2}')
DRIFT=0
for page in website/index.html website/about.html website/download.html; do
    grep -q "$VERSION" "$page" || { echo "WARN: $page does not mention version $VERSION" >&2; DRIFT=1; }
done
grep -q "version: \"$VERSION\"" CITATION.cff || {
    echo "WARN: CITATION.cff is not at version $VERSION" >&2; DRIFT=1; }
# The app reports its own version in Help and diagnostics; about.html
# tells users to look there, so it must agree with the site. Check both
# things the site serves: the split web app (where the declaration now
# lives in the hashed shell script, not index.html) and the portable
# download. Anchored on the DECLARATION, since a bare version grep
# passes vacuously off a vendored library that contains the string.
grep -rq "APP_VERSION = \"$VERSION\"" website/app/lib || {
    echo "WARN: the web app does not declare APP_VERSION = $VERSION" >&2; DRIFT=1; }
grep -q "APP_VERSION = \"$VERSION\"" website/pandion-plots.html || {
    echo "WARN: the portable download does not declare APP_VERSION = $VERSION" >&2; DRIFT=1; }
if [ "$DRIFT" = "0" ]; then
    echo "version $VERSION consistent across the site + CITATION.cff"
else
    echo "ERROR: public version references are inconsistent" >&2
    exit 1
fi

node website/verify-accessibility.mjs
