
# This file is automatically generated, you probably don't want to edit this

freqplotbuilderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "freqplotbuilderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            annotationsJson = "",
            chartSnapshot = "",
            clientBundleHash = "",
            exportPath = "",
            exportRequest = "",
            facetVar = NULL,
            freqPosition = "dodge",
            freqStat = "count",
            graphType = "bar",
            groupVar = NULL,
            paletteLibrary = "",
            styleLibrary = "",
            styleStamp = FALSE,
            var = NULL,
            chartSpec = "", ...) {

            super$initialize(
                package="pandion",
                name="freqplotbuilder",
                requiresData=TRUE,
                ...)

            private$..annotationsJson <- jmvcore::OptionString$new(
                "annotationsJson",
                annotationsJson,
                default="",
                hidden=TRUE)
            private$..chartSnapshot <- jmvcore::OptionString$new(
                "chartSnapshot",
                chartSnapshot,
                default="",
                hidden=TRUE)
            private$..clientBundleHash <- jmvcore::OptionString$new(
                "clientBundleHash",
                clientBundleHash,
                default="",
                hidden=TRUE)
            private$..exportPath <- jmvcore::OptionString$new(
                "exportPath",
                exportPath,
                default="",
                hidden=TRUE)
            private$..exportRequest <- jmvcore::OptionString$new(
                "exportRequest",
                exportRequest,
                default="",
                hidden=TRUE)
            private$..facetVar <- jmvcore::OptionVariable$new(
                "facetVar",
                facetVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..freqPosition <- jmvcore::OptionList$new(
                "freqPosition",
                freqPosition,
                hidden=TRUE,
                options=list(
                    "dodge",
                    "stack",
                    "fill"),
                default="dodge")
            private$..freqStat <- jmvcore::OptionList$new(
                "freqStat",
                freqStat,
                hidden=TRUE,
                options=list(
                    "count",
                    "percent",
                    "proportion"),
                default="count")
            private$..graphType <- jmvcore::OptionList$new(
                "graphType",
                graphType,
                hidden=TRUE,
                options=list(
                    "bar",
                    "pie",
                    "donut",
                    "pareto"),
                default="bar")
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..paletteLibrary <- jmvcore::OptionString$new(
                "paletteLibrary",
                paletteLibrary,
                default="",
                hidden=TRUE)
            private$..styleLibrary <- jmvcore::OptionString$new(
                "styleLibrary",
                styleLibrary,
                default="",
                hidden=TRUE)
            private$..styleStamp <- jmvcore::OptionBool$new(
                "styleStamp",
                styleStamp,
                default=FALSE,
                hidden=TRUE)
            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..chartSpec <- jmvcore::OptionString$new(
                "chartSpec",
                chartSpec,
                default="",
                hidden=TRUE)

            self$.addOption(private$..annotationsJson)
            self$.addOption(private$..chartSnapshot)
            self$.addOption(private$..clientBundleHash)
            self$.addOption(private$..exportPath)
            self$.addOption(private$..exportRequest)
            self$.addOption(private$..facetVar)
            self$.addOption(private$..freqPosition)
            self$.addOption(private$..freqStat)
            self$.addOption(private$..graphType)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..paletteLibrary)
            self$.addOption(private$..styleLibrary)
            self$.addOption(private$..styleStamp)
            self$.addOption(private$..var)
            self$.addOption(private$..chartSpec)
        }),
    active = list(
        annotationsJson = function() private$..annotationsJson$value,
        chartSnapshot = function() private$..chartSnapshot$value,
        clientBundleHash = function() private$..clientBundleHash$value,
        exportPath = function() private$..exportPath$value,
        exportRequest = function() private$..exportRequest$value,
        facetVar = function() private$..facetVar$value,
        freqPosition = function() private$..freqPosition$value,
        freqStat = function() private$..freqStat$value,
        graphType = function() private$..graphType$value,
        groupVar = function() private$..groupVar$value,
        paletteLibrary = function() private$..paletteLibrary$value,
        styleLibrary = function() private$..styleLibrary$value,
        styleStamp = function() private$..styleStamp$value,
        var = function() private$..var$value,
        chartSpec = function() private$..chartSpec$value),
    private = list(
        ..annotationsJson = NA,
        ..chartSnapshot = NA,
        ..clientBundleHash = NA,
        ..exportPath = NA,
        ..exportRequest = NA,
        ..facetVar = NA,
        ..freqPosition = NA,
        ..freqStat = NA,
        ..graphType = NA,
        ..groupVar = NA,
        ..paletteLibrary = NA,
        ..styleLibrary = NA,
        ..styleStamp = NA,
        ..var = NA,
        ..chartSpec = NA)
)

freqplotbuilderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "freqplotbuilderResults",
    inherit = jmvcore::Group,
    active = list(
        widget = function() private$.items[["widget"]],
        snapshotImage = function() private$.items[["snapshotImage"]],
        exportStatus = function() private$.items[["exportStatus"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Frequencies")
            self$add(jmvcore::Html$new(
                options=options,
                name="widget",
                title="Frequencies",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="snapshotImage",
                title="Chart (static copy)",
                width=700,
                height=450,
                renderFun=".renderSnapshot",
                clearWith=list(
                    "chartSnapshot"),
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="exportStatus",
                title="Export Status",
                visible=TRUE))}))

freqplotbuilderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "freqplotbuilderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pandion",
                name = "freqplotbuilder",
                version = c(0,0,1),
                options = options,
                results = freqplotbuilderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Frequencies
#'
#' Summarize the counts or proportions of a categorical variable. Draws 
#' side-by-side, stacked, or 100\% stacked bar charts, pie or donut charts, 
#' and Pareto charts, with percentage or count labels. The Statistics panel 
#' reports chi-square tests, standardized residuals, proportion comparisons, 
#' and counts. Group and facet to break the counts down further.
#' 
#' @param annotationsJson .
#' @param chartSnapshot .
#' @param clientBundleHash .
#' @param data .
#' @param exportPath .
#' @param exportRequest .
#' @param facetVar .
#' @param freqPosition .
#' @param freqStat .
#' @param graphType .
#' @param groupVar .
#' @param paletteLibrary .
#' @param styleLibrary .
#' @param styleStamp .
#' @param var .
#' @param chartSpec .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$widget} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$snapshotImage} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$exportStatus} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
freqplotbuilder <- function(
    annotationsJson = "",
    chartSnapshot = "",
    clientBundleHash = "",
    data,
    exportPath = "",
    exportRequest = "",
    facetVar,
    freqPosition = "dodge",
    freqStat = "count",
    graphType = "bar",
    groupVar,
    paletteLibrary = "",
    styleLibrary = "",
    styleStamp = FALSE,
    var,
    chartSpec = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("freqplotbuilder requires jmvcore to be installed (restart may be required)")

    if ( ! missing(facetVar)) facetVar <- jmvcore::resolveQuo(jmvcore::enquo(facetVar))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(facetVar), facetVar, NULL),
            `if`( ! missing(groupVar), groupVar, NULL),
            `if`( ! missing(var), var, NULL))

    for (v in facetVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- freqplotbuilderOptions$new(
        annotationsJson = annotationsJson,
        chartSnapshot = chartSnapshot,
        clientBundleHash = clientBundleHash,
        exportPath = exportPath,
        exportRequest = exportRequest,
        facetVar = facetVar,
        freqPosition = freqPosition,
        freqStat = freqStat,
        graphType = graphType,
        groupVar = groupVar,
        paletteLibrary = paletteLibrary,
        styleLibrary = styleLibrary,
        styleStamp = styleStamp,
        var = var,
        chartSpec = chartSpec)

    analysis <- freqplotbuilderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

